### ISSUE TITLE
not supporting angular 1.6

### ISSUE THREAD

**Issue by puregold117** [lynndylanhurley/ng-token-auth#347]
I get this error using with angular1.6
```
$http.post(...).success is not a function
```
still not supporting angular1.6?

**Comment by puregold117** [comment]
Here's dependencies
```
"dependencies": {
"angular": ">=1.4 <=1.5.3",
"angular-cookie": "~4.1.0"
}
```

**Comment by deric** [comment]
Should be fixed by #226.

**Comment by puregold117** [comment]
Right. thank you @deric. I had to write my own token  module.

**Comment by itaditya** [comment]
I was having the same issue ,so I used `then` in place of `success` in your module . It's working now , but the events are not broadcasting

**Comment by andreneto** [comment]
Any updates on this release?

**Comment by zoamel** [comment]
Yeah, this is still an issue, and only thing that stops me from upgrading my app to angular 1.6 :(

**Comment by Adi9** [comment]
Same here - bower refuses to install for angular 1.6.3

**Comment by thetomja** [comment]
26 April 2017 and it's still an issue. Could you please draft a release as many people seem to be complaining about this same issue, and it seems to be fixed in the [latest commit on master](https://github.com/lynndylanhurley/ng-token-auth/commit/d5d3d616ebee07d09facb2a408c0add7005042b4) after a recently merged PR.

**Comment by booleanbetrayal** [comment]
A new release was cut. Closing.
